import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api, type RouterOutputs } from "~/utils/api";
import { Header } from "../components/Header";
import { useState, type FormEvent, type ChangeEvent } from "react";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Recipe Book</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <h1>Welcome to the homepage!</h1>
        <Link href="/myRecipes">Go to My Recipes!</Link>
        <br></br>
        <Link href="/createRecipe">Add A Recipe!</Link>
      </main>
    </>
  );
}
